language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - cd test/code/
  - pytest test_explicit_cf_recommenders.py
  - pytest test_implicit_surprise_cf_recommenders.py